### ISSUE TITLE
Change times variables to use struct

### ISSUE THREAD

**Issue by pantuza** [pantuza/wake-up-at#1]
We need to change the following variables to a struct. Then, use functions as struct member to control scope. Do not forget to refactory tests.

``` go
first_time
second_time
third_time
fourth_time
```

**Comment by dnsaoki2** [comment]
@pantuza i would like to take this issue :)

**Comment by pantuza** [comment]
Solved in [Pull request 3](https://github.com/pantuza/wake-up-at/pull/3)
